services:
  - type: web
    name: visionshield-ui
    runtime: docker
    plan: free
    healthCheckPath: /api/health
    autoDeploy: true
  - type: web
    name: visionshield-ev-location-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    plan: free
    healthCheckPath: /health
    autoDeploy: true
